version: '2'

services:
  webserver:
    build: ./etc/docker
    image: simple_lamp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/site
      - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
      - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=userpassword
